AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  testregistdata:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: >-
        arn:aws:iam::xxxxxxxxxxxx:role/service-role/test_regist_data-role-cotewp0d
      VpcConfig:
        SecurityGroupIds:
          - sg-c4b48ab0
        SubnetIds:
          - subnet-0f340e54
          - subnet-4ace1d61
      Layers:
        - >-
          arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-python38-pandas:33
        - >-
          arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-python38-SQLAlchemy:22
        - >-
          arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-python38-aws-psycopg2:1
